DecisionTreeClassifier:
  "default":
    { }
  "random_search":
    "criterion": [ "gini", "entropy" ]
    "max_depth": [ 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
    "min_samples_split": [ 2, 5, 10, 15, 20, 25 ]
    "min_samples_leaf": [ 2, 4, 6, 8, 10 ]
    "random_state": [ 17 ]
  "grid_search":
    "criterion": [ "gini", "entropy" ]
    "max_depth": [ 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
    "min_samples_split": [ 2, 5, 10, 15, 20, 25 ]
    "min_samples_leaf": [ 2, 4, 6, 8, 10 ]
    "random_state": [ 17 ]
  "CV": 8

RandomForestClassifier:
  "default":
    { }
  "random_search":
#    'n_estimators': [ 50, 100, 200, 400 ]
#    'criterion': [ 'gini', 'entropy' ]
#    'max_depth': [ 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
#    'min_samples_split': [ 2, 5, 10, 15, 20, 25 ]
#    'min_samples_leaf': [ 2, 4, 6, 8, 10 ]
    { }
  "grid_search":
    { }
  "CV": 8

GradientBoostingClassifier:
  "default":
    { }
  "random_search":
#    'learning_rate': [ 0.01, 0.02, 0.05, 0.07, 0.09, 0.1, 0.3, 0.5, 0.005 ]
#    'n_estimators': [ 50, 100, 200, 400 ]
#    'criterion': [ 'friedman_mse', 'squared_error' ]
#    'min_samples_leaf': [ 2, 4, 6, 8, 10 ]
#    'min_samples_split': [ 2, 5, 10, 15, 20, 25 ]
#    'max_depth': [ 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
    { }
  "grid_search":
    { }
  "CV": 8

AdaBoostClassifier:
  "default":
    { }
  "random_search":
#    'learning_rate': [ 0.01, 0.02, 0.05, 0.07, 0.09, 0.1, 0.3, 0.5, 0.005 ]
#    'n_estimators': [ 50, 100, 200, 400 ]
    { }
  "grid_search":
    { }
  "CV": 8

XGBClassifier:
  "default":
    { }
  "random_search":
#    'learning_rate': [ 0.01, 0.03]
#    'learning_rate': [ 0.01, 0.03, 0.05, 0.1, 0.3, 0.5, 0.8 ]
#    'max_depth': [ 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
#    'min_child_weight': [ 1, 3, 5, 7, 9 ]
#    'subsample': [ 0.1, 0.3, 0.5, 0.7, 0.9 ]
#    'colsample_bytree': [ 0.1, 0.3, 0.5, 0.7, 0.9 ]
#    'n_estimators': [ 50, 100, 200, 400 ]
#    'gamma': [ 0.1, 0.3, 0.5, 0.7, 0.9 ]
#    'reg_alpha': [ 0.1, 0.3, 0.5, 0.7, 0.9 ]
#    'reg_lambda': [ 0.1, 0.3, 0.5, 0.7, 0.9 ]
#    'scale_pos_weight': [ 4 ]
    { }
  "grid_search":
    { }
  "CV": 8